import json

words = [
  # ── LEVEL 5 · Arc 2 · Rio de Janeiro – Chegada ──────────────────────────
  {"id":221,"pt":"então","en":"so / then","pos":"adverb","level":5,"arc":2,
   "sentences":[{"pt":"Então, o que você quer fazer hoje?","en":"So, what do you want to do today?"},
                {"pt":"Estava cansado, então fui dormir cedo.","en":"I was tired, so I went to sleep early."}]},
  {"id":222,"pt":"assim","en":"like this / that way / so","pos":"adverb","level":5,"arc":2,
   "sentences":[{"pt":"Não faz assim, faz desse jeito.","en":"Don't do it like that, do it this way."},
                {"pt":"Assim fica melhor.","en":"That way it's better."}]},
  {"id":223,"pt":"né","en":"right? / isn't it? (discourse marker)","pos":"interjection","level":5,"arc":2,
   "sentences":[{"pt":"Você vai à festa, né?","en":"You're going to the party, right?"},
                {"pt":"Tá bom, né?","en":"It's good, right?"}]},
  {"id":224,"pt":"tá","en":"ok / alright / it's (colloquial)","pos":"interjection","level":5,"arc":2,
   "sentences":[{"pt":"Tá, pode deixar que eu resolvo.","en":"Ok, leave it to me, I'll take care of it."},
                {"pt":"Tá bom, a gente vai.","en":"Alright, we'll go."}]},
  {"id":225,"pt":"cara","en":"dude / face (colloquial)","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Cara, que legal esse lugar!","en":"Dude, this place is so cool!"},
                {"pt":"Esse cara é muito engraçado.","en":"That guy is really funny."}]},
  {"id":226,"pt":"a gente","en":"we / us (colloquial)","pos":"pronoun","level":5,"arc":2,
   "sentences":[{"pt":"A gente vai à praia amanhã.","en":"We're going to the beach tomorrow."},
                {"pt":"A gente pode resolver isso juntos.","en":"We can solve this together."}]},
  {"id":227,"pt":"vez","en":"time / instance / turn","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Essa é a primeira vez que eu venho ao Rio.","en":"This is the first time I've come to Rio."},
                {"pt":"Já fui lá várias vezes.","en":"I've been there many times."}]},
  {"id":228,"pt":"amor","en":"love","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"O amor dela pelo Brasil é enorme.","en":"Her love for Brazil is enormous."},
                {"pt":"Amor é a base de tudo.","en":"Love is the foundation of everything."}]},
  {"id":229,"pt":"medo","en":"fear","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Tenho medo de altura.","en":"I'm afraid of heights."},
                {"pt":"Não tenha medo de errar.","en":"Don't be afraid to make mistakes."}]},
  {"id":230,"pt":"sorte","en":"luck","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Boa sorte na prova!","en":"Good luck on the test!"},
                {"pt":"Foi sorte encontrá-lo aqui.","en":"It was luck running into you here."}]},
  {"id":231,"pt":"paz","en":"peace","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Preciso de paz e silêncio para trabalhar.","en":"I need peace and quiet to work."},
                {"pt":"O Rio tem uma energia de paz na praia.","en":"Rio has a peaceful energy at the beach."}]},
  {"id":232,"pt":"força","en":"strength / force / come on!","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Força! Você consegue!","en":"Come on! You can do it!"},
                {"pt":"Ela tem muita força de vontade.","en":"She has a lot of willpower."}]},
  {"id":233,"pt":"sonho","en":"dream","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Meu sonho é morar no Brasil.","en":"My dream is to live in Brazil."},
                {"pt":"Tive um sonho estranho essa noite.","en":"I had a strange dream last night."}]},
  {"id":234,"pt":"coração","en":"heart","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Meu coração acelera quando ouço essa música.","en":"My heart races when I hear that music."},
                {"pt":"Fala do coração.","en":"Speak from the heart."}]},
  {"id":235,"pt":"irmão","en":"brother","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Meu irmão mora em São Paulo.","en":"My brother lives in São Paulo."},
                {"pt":"Somos irmãos, nos ajudamos sempre.","en":"We are brothers, we always help each other."}]},
  {"id":236,"pt":"irmã","en":"sister","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Minha irmã é mais nova do que eu.","en":"My sister is younger than me."},
                {"pt":"Ela e a irmã são muito parecidas.","en":"She and her sister look very alike."}]},
  {"id":237,"pt":"namorado","en":"boyfriend","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Meu namorado é carioca.","en":"My boyfriend is from Rio."},
                {"pt":"Você tem namorado?","en":"Do you have a boyfriend?"}]},
  {"id":238,"pt":"namorada","en":"girlfriend","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"A namorada dele é muito simpática.","en":"His girlfriend is very friendly."},
                {"pt":"Eles namoram há dois anos.","en":"They've been dating for two years."}]},
  {"id":239,"pt":"marido","en":"husband","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"O marido dela é médico.","en":"Her husband is a doctor."},
                {"pt":"Meu marido adora cozinhar.","en":"My husband loves to cook."}]},
  {"id":240,"pt":"esposa","en":"wife","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"A esposa dele é professora.","en":"His wife is a teacher."},
                {"pt":"Minha esposa e eu viajamos muito.","en":"My wife and I travel a lot."}]},
  {"id":241,"pt":"criança","en":"child","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"As crianças adoram brincar na praia.","en":"Children love to play at the beach."},
                {"pt":"Quando eu era criança, morava no interior.","en":"When I was a child, I lived in the countryside."}]},
  {"id":242,"pt":"homem","en":"man","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"Aquele homem trabalha na prefeitura.","en":"That man works at city hall."},
                {"pt":"Há muitos homens e mulheres na fila.","en":"There are many men and women in the line."}]},
  {"id":243,"pt":"mulher","en":"woman / wife","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"A mulher pediu informações sobre o metrô.","en":"The woman asked for information about the subway."},
                {"pt":"Ela é uma mulher muito inteligente.","en":"She is a very intelligent woman."}]},
  {"id":244,"pt":"menino","en":"boy","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"O menino está jogando bola na rua.","en":"The boy is playing ball in the street."},
                {"pt":"Quando era menino, adorava futebol.","en":"When he was a boy, he loved soccer."}]},
  {"id":245,"pt":"menina","en":"girl","pos":"noun","level":5,"arc":2,
   "sentences":[{"pt":"A menina ganhou um prêmio na escola.","en":"The girl won a prize at school."},
                {"pt":"Ela era uma menina muito curiosa.","en":"She was a very curious girl."}]},
  {"id":246,"pt":"jovem","en":"young / young person","pos":"adjective","level":5,"arc":2,
   "sentences":[{"pt":"Ela é jovem e cheia de energia.","en":"She is young and full of energy."},
                {"pt":"Os jovens do Brasil adoram música.","en":"Young people in Brazil love music."}]},
  # Verbs level 5
  {"id":247,"pt":"deixar","en":"to leave / to let / to allow","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Deixa eu explicar.","en":"Let me explain."},
                {"pt":"Deixei meu celular no hotel.","en":"I left my phone at the hotel."}],
   "conjugations":{"presente":{"eu":"deixo","tu":"deixas","ele":"deixa","nos":"deixamos","vcs":"deixam"},
                   "perfeito":{"eu":"deixei","tu":"deixaste","ele":"deixou","nos":"deixamos","vcs":"deixaram"},
                   "imperfeito":{"eu":"deixava","tu":"deixavas","ele":"deixava","nos":"deixávamos","vcs":"deixavam"},
                   "futuro":{"eu":"deixarei","tu":"deixarás","ele":"deixará","nos":"deixaremos","vcs":"deixarão"}}},
  {"id":248,"pt":"começar","en":"to begin / to start","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"A aula começa às oito horas.","en":"The class starts at eight o'clock."},
                {"pt":"Vamos começar do zero.","en":"Let's start from scratch."}],
   "conjugations":{"presente":{"eu":"começo","tu":"começas","ele":"começa","nos":"começamos","vcs":"começam"},
                   "perfeito":{"eu":"comecei","tu":"começaste","ele":"começou","nos":"começamos","vcs":"começaram"},
                   "imperfeito":{"eu":"começava","tu":"começavas","ele":"começava","nos":"começávamos","vcs":"começavam"},
                   "futuro":{"eu":"começarei","tu":"começarás","ele":"começará","nos":"começaremos","vcs":"começarão"}}},
  {"id":249,"pt":"acabar","en":"to finish / to end / to run out","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"A festa acabou tarde.","en":"The party ended late."},
                {"pt":"Acabou o dinheiro, preciso ir ao banco.","en":"The money ran out, I need to go to the bank."}],
   "conjugations":{"presente":{"eu":"acabo","tu":"acabas","ele":"acaba","nos":"acabamos","vcs":"acabam"},
                   "perfeito":{"eu":"acabei","tu":"acabaste","ele":"acabou","nos":"acabamos","vcs":"acabaram"},
                   "imperfeito":{"eu":"acabava","tu":"acabavas","ele":"acabava","nos":"acabávamos","vcs":"acabavam"},
                   "futuro":{"eu":"acabarei","tu":"acabarás","ele":"acabará","nos":"acabaremos","vcs":"acabarão"}}},
  {"id":250,"pt":"continuar","en":"to continue / to keep going","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Continue estudando, você vai conseguir.","en":"Keep studying, you'll get it."},
                {"pt":"A chuva continuou por horas.","en":"The rain continued for hours."}],
   "conjugations":{"presente":{"eu":"continuo","tu":"continuas","ele":"continua","nos":"continuamos","vcs":"continuam"},
                   "perfeito":{"eu":"continuei","tu":"continuaste","ele":"continuou","nos":"continuamos","vcs":"continuaram"},
                   "imperfeito":{"eu":"continuava","tu":"continuavas","ele":"continuava","nos":"continuávamos","vcs":"continuavam"},
                   "futuro":{"eu":"continuarei","tu":"continuarás","ele":"continuará","nos":"continuaremos","vcs":"continuarão"}}},
  {"id":251,"pt":"acontecer","en":"to happen","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"O que aconteceu?","en":"What happened?"},
                {"pt":"Isso nunca vai acontecer de novo.","en":"This will never happen again."}],
   "conjugations":{"presente":{"eu":"aconteço","tu":"aconteces","ele":"acontece","nos":"acontecemos","vcs":"acontecem"},
                   "perfeito":{"eu":"aconteci","tu":"aconteceste","ele":"aconteceu","nos":"acontecemos","vcs":"aconteceram"},
                   "imperfeito":{"eu":"acontecia","tu":"acontecias","ele":"acontecia","nos":"acontecíamos","vcs":"aconteciam"},
                   "futuro":{"eu":"acontecerei","tu":"acontecerás","ele":"acontecerá","nos":"aconteceremos","vcs":"acontecerão"}}},
  {"id":252,"pt":"trazer","en":"to bring","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Traz uma garrafa de água, por favor.","en":"Bring a bottle of water, please."},
                {"pt":"Ele trouxe um presente para mim.","en":"He brought a gift for me."}],
   "conjugations":{"presente":{"eu":"trago","tu":"trazes","ele":"traz","nos":"trazemos","vcs":"trazem"},
                   "perfeito":{"eu":"trouxe","tu":"trouxeste","ele":"trouxe","nos":"trouxemos","vcs":"trouxeram"},
                   "imperfeito":{"eu":"trazia","tu":"trazias","ele":"trazia","nos":"trazíamos","vcs":"traziam"},
                   "futuro":{"eu":"trarei","tu":"trarás","ele":"trará","nos":"traremos","vcs":"trarão"}}},
  {"id":253,"pt":"tirar","en":"to take out / to remove / to take (a photo)","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Posso tirar uma foto sua?","en":"Can I take a photo of you?"},
                {"pt":"Tira os sapatos antes de entrar.","en":"Take off your shoes before entering."}],
   "conjugations":{"presente":{"eu":"tiro","tu":"tiras","ele":"tira","nos":"tiramos","vcs":"tiram"},
                   "perfeito":{"eu":"tirei","tu":"tiraste","ele":"tirou","nos":"tiramos","vcs":"tiraram"},
                   "imperfeito":{"eu":"tirava","tu":"tiravas","ele":"tirava","nos":"tirávamos","vcs":"tiravam"},
                   "futuro":{"eu":"tirarei","tu":"tirarás","ele":"tirará","nos":"tiraremos","vcs":"tirarão"}}},
  {"id":254,"pt":"pagar","en":"to pay","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Quem vai pagar a conta?","en":"Who's going to pay the bill?"},
                {"pt":"Paguei com cartão.","en":"I paid with a card."}],
   "conjugations":{"presente":{"eu":"pago","tu":"pagas","ele":"paga","nos":"pagamos","vcs":"pagam"},
                   "perfeito":{"eu":"paguei","tu":"pagaste","ele":"pagou","nos":"pagamos","vcs":"pagaram"},
                   "imperfeito":{"eu":"pagava","tu":"pagavas","ele":"pagava","nos":"pagávamos","vcs":"pagavam"},
                   "futuro":{"eu":"pagarei","tu":"pagarás","ele":"pagará","nos":"pagaremos","vcs":"pagarão"}}},
  {"id":255,"pt":"perder","en":"to lose / to miss (bus, etc.)","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Perdi meu passaporte no aeroporto.","en":"I lost my passport at the airport."},
                {"pt":"Não perde o ônibus das oito!","en":"Don't miss the eight o'clock bus!"}],
   "conjugations":{"presente":{"eu":"perco","tu":"perdes","ele":"perde","nos":"perdemos","vcs":"perdem"},
                   "perfeito":{"eu":"perdi","tu":"perdeste","ele":"perdeu","nos":"perdemos","vcs":"perderam"},
                   "imperfeito":{"eu":"perdia","tu":"perdias","ele":"perdia","nos":"perdíamos","vcs":"perdiam"},
                   "futuro":{"eu":"perderei","tu":"perderás","ele":"perderá","nos":"perderemos","vcs":"perderão"}}},
  {"id":256,"pt":"mostrar","en":"to show","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Me mostra o caminho para a praia.","en":"Show me the way to the beach."},
                {"pt":"Ela mostrou as fotos da viagem.","en":"She showed the travel photos."}],
   "conjugations":{"presente":{"eu":"mostro","tu":"mostras","ele":"mostra","nos":"mostramos","vcs":"mostram"},
                   "perfeito":{"eu":"mostrei","tu":"mostraste","ele":"mostrou","nos":"mostramos","vcs":"mostraram"},
                   "imperfeito":{"eu":"mostrava","tu":"mostravas","ele":"mostrava","nos":"mostrávamos","vcs":"mostravam"},
                   "futuro":{"eu":"mostrarei","tu":"mostrarás","ele":"mostrará","nos":"mostraremos","vcs":"mostrarão"}}},
  {"id":257,"pt":"colocar","en":"to put / to place","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Coloca a mala no quarto.","en":"Put the suitcase in the room."},
                {"pt":"Onde eu coloco isso?","en":"Where do I put this?"}],
   "conjugations":{"presente":{"eu":"coloco","tu":"colocas","ele":"coloca","nos":"colocamos","vcs":"colocam"},
                   "perfeito":{"eu":"coloquei","tu":"colocaste","ele":"colocou","nos":"colocamos","vcs":"colocaram"},
                   "imperfeito":{"eu":"colocava","tu":"colocavas","ele":"colocava","nos":"colocávamos","vcs":"colocavam"},
                   "futuro":{"eu":"colocarei","tu":"colocarás","ele":"colocará","nos":"colocaremos","vcs":"colocarão"}}},
  {"id":258,"pt":"levar","en":"to take / to carry / to bring (somewhere)","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Leva um guarda-chuva, vai chover.","en":"Take an umbrella, it's going to rain."},
                {"pt":"Ela levou os filhos à escola.","en":"She took the kids to school."}],
   "conjugations":{"presente":{"eu":"levo","tu":"levas","ele":"leva","nos":"levamos","vcs":"levam"},
                   "perfeito":{"eu":"levei","tu":"levaste","ele":"levou","nos":"levamos","vcs":"levaram"},
                   "imperfeito":{"eu":"levava","tu":"levavas","ele":"levava","nos":"levávamos","vcs":"levavam"},
                   "futuro":{"eu":"levarei","tu":"levarás","ele":"levará","nos":"levaremos","vcs":"levarão"}}},
  {"id":259,"pt":"ouvir","en":"to hear / to listen","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Você ouviu o que eu disse?","en":"Did you hear what I said?"},
                {"pt":"Adoro ouvir música brasileira.","en":"I love listening to Brazilian music."}],
   "conjugations":{"presente":{"eu":"ouço","tu":"ouves","ele":"ouve","nos":"ouvimos","vcs":"ouvem"},
                   "perfeito":{"eu":"ouvi","tu":"ouviste","ele":"ouviu","nos":"ouvimos","vcs":"ouviram"},
                   "imperfeito":{"eu":"ouvia","tu":"ouvias","ele":"ouvia","nos":"ouv\u00edamos","vcs":"ouviam"},
                   "futuro":{"eu":"ouvirei","tu":"ouvirás","ele":"ouvirá","nos":"ouviremos","vcs":"ouvirão"}}},
  {"id":260,"pt":"sair","en":"to leave / to go out","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"A gente sai às dez?","en":"Shall we head out at ten?"},
                {"pt":"Ela saiu cedo essa manhã.","en":"She left early this morning."}],
   "conjugations":{"presente":{"eu":"saio","tu":"sais","ele":"sai","nos":"saímos","vcs":"saem"},
                   "perfeito":{"eu":"saí","tu":"saíste","ele":"saiu","nos":"saímos","vcs":"saíram"},
                   "imperfeito":{"eu":"saía","tu":"saías","ele":"saía","nos":"saíamos","vcs":"saíam"},
                   "futuro":{"eu":"sairei","tu":"sairás","ele":"sairá","nos":"sairemos","vcs":"sairão"}}},
  {"id":261,"pt":"entrar","en":"to enter / to come in","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Pode entrar, a porta está aberta.","en":"You can come in, the door is open."},
                {"pt":"Entramos no restaurante com fome.","en":"We entered the restaurant hungry."}],
   "conjugations":{"presente":{"eu":"entro","tu":"entras","ele":"entra","nos":"entramos","vcs":"entram"},
                   "perfeito":{"eu":"entrei","tu":"entraste","ele":"entrou","nos":"entramos","vcs":"entraram"},
                   "imperfeito":{"eu":"entrava","tu":"entravas","ele":"entrava","nos":"entrávamos","vcs":"entravam"},
                   "futuro":{"eu":"entrarei","tu":"entrarás","ele":"entrará","nos":"entraremos","vcs":"entrarão"}}},
  {"id":262,"pt":"passar","en":"to pass / to spend (time) / to go through","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Passamos uma semana em Florianópolis.","en":"We spent a week in Florianópolis."},
                {"pt":"O ônibus passa aqui a cada meia hora.","en":"The bus passes here every half hour."}],
   "conjugations":{"presente":{"eu":"passo","tu":"passas","ele":"passa","nos":"passamos","vcs":"passam"},
                   "perfeito":{"eu":"passei","tu":"passaste","ele":"passou","nos":"passamos","vcs":"passaram"},
                   "imperfeito":{"eu":"passava","tu":"passavas","ele":"passava","nos":"passávamos","vcs":"passavam"},
                   "futuro":{"eu":"passarei","tu":"passarás","ele":"passará","nos":"passaremos","vcs":"passarão"}}},
  {"id":263,"pt":"correr","en":"to run","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Ele corre na praia todo dia de manhã.","en":"He runs on the beach every morning."},
                {"pt":"Corre, o ônibus vai embora!","en":"Run, the bus is leaving!"}],
   "conjugations":{"presente":{"eu":"corro","tu":"corres","ele":"corre","nos":"corremos","vcs":"correm"},
                   "perfeito":{"eu":"corri","tu":"correste","ele":"correu","nos":"corremos","vcs":"correram"},
                   "imperfeito":{"eu":"corria","tu":"corrias","ele":"corria","nos":"corríamos","vcs":"corriam"},
                   "futuro":{"eu":"correrei","tu":"correrás","ele":"correrá","nos":"correremos","vcs":"correrão"}}},
  {"id":264,"pt":"seguir","en":"to follow / to continue straight","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Segue em frente e vira na esquerda.","en":"Go straight and turn left."},
                {"pt":"Sigo as instruções do mapa.","en":"I follow the instructions on the map."}],
   "conjugations":{"presente":{"eu":"sigo","tu":"segues","ele":"segue","nos":"seguimos","vcs":"seguem"},
                   "perfeito":{"eu":"segui","tu":"seguiste","ele":"seguiu","nos":"seguimos","vcs":"seguiram"},
                   "imperfeito":{"eu":"seguia","tu":"seguias","ele":"seguia","nos":"seguíamos","vcs":"seguiam"},
                   "futuro":{"eu":"seguirei","tu":"seguirás","ele":"seguirá","nos":"seguiremos","vcs":"seguirão"}}},
  {"id":265,"pt":"escolher","en":"to choose / to pick","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Você já escolheu o que vai comer?","en":"Have you already chosen what you're going to eat?"},
                {"pt":"Escolhe qualquer um, todos são bons.","en":"Pick any one, they're all good."}],
   "conjugations":{"presente":{"eu":"escolho","tu":"escolhes","ele":"escolhe","nos":"escolhemos","vcs":"escolhem"},
                   "perfeito":{"eu":"escolhi","tu":"escolheste","ele":"escolheu","nos":"escolhemos","vcs":"escolheram"},
                   "imperfeito":{"eu":"escolhia","tu":"escolhias","ele":"escolhia","nos":"escolhíamos","vcs":"escolhiam"},
                   "futuro":{"eu":"escolherei","tu":"escolherás","ele":"escolherá","nos":"escolheremos","vcs":"escolherão"}}},
  {"id":266,"pt":"ganhar","en":"to win / to earn / to gain","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"O Brasil ganhou a Copa do Mundo em 1970.","en":"Brazil won the World Cup in 1970."},
                {"pt":"Quanto você ganha por mês?","en":"How much do you earn per month?"}],
   "conjugations":{"presente":{"eu":"ganho","tu":"ganhas","ele":"ganha","nos":"ganhamos","vcs":"ganham"},
                   "perfeito":{"eu":"ganhei","tu":"ganhaste","ele":"ganhou","nos":"ganhamos","vcs":"ganharam"},
                   "imperfeito":{"eu":"ganhava","tu":"ganhavas","ele":"ganhava","nos":"ganhávamos","vcs":"ganhavam"},
                   "futuro":{"eu":"ganharei","tu":"ganharás","ele":"ganhará","nos":"ganharemos","vcs":"ganharão"}}},
  {"id":267,"pt":"tentar","en":"to try / to attempt","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Tenta mais uma vez!","en":"Try one more time!"},
                {"pt":"Tentei falar em português o dia todo.","en":"I tried to speak in Portuguese all day."}],
   "conjugations":{"presente":{"eu":"tento","tu":"tentas","ele":"tenta","nos":"tentamos","vcs":"tentam"},
                   "perfeito":{"eu":"tentei","tu":"tentaste","ele":"tentou","nos":"tentamos","vcs":"tentaram"},
                   "imperfeito":{"eu":"tentava","tu":"tentavas","ele":"tentava","nos":"tentávamos","vcs":"tentavam"},
                   "futuro":{"eu":"tentarei","tu":"tentarás","ele":"tentará","nos":"tentaremos","vcs":"tentarão"}}},
  {"id":268,"pt":"conseguir","en":"to manage / to succeed / to get","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Finalmente consegui um ingresso para o show.","en":"I finally managed to get a ticket to the show."},
                {"pt":"Você consegue falar devagar?","en":"Can you speak slowly?"}],
   "conjugations":{"presente":{"eu":"consigo","tu":"consegues","ele":"consegue","nos":"conseguimos","vcs":"conseguem"},
                   "perfeito":{"eu":"consegui","tu":"conseguiste","ele":"conseguiu","nos":"conseguimos","vcs":"conseguiram"},
                   "imperfeito":{"eu":"conseguia","tu":"conseguias","ele":"conseguia","nos":"conseguíamos","vcs":"conseguiam"},
                   "futuro":{"eu":"conseguirei","tu":"conseguirás","ele":"conseguirá","nos":"conseguiremos","vcs":"conseguirão"}}},
  {"id":269,"pt":"chamar","en":"to call / to name / to summon","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Como você se chama?","en":"What's your name? (What do you call yourself?)"},
                {"pt":"Chama um táxi, por favor.","en":"Call a cab, please."}],
   "conjugations":{"presente":{"eu":"chamo","tu":"chamas","ele":"chama","nos":"chamamos","vcs":"chamam"},
                   "perfeito":{"eu":"chamei","tu":"chamaste","ele":"chamou","nos":"chamamos","vcs":"chamaram"},
                   "imperfeito":{"eu":"chamava","tu":"chamavas","ele":"chamava","nos":"chamávamos","vcs":"chamavam"},
                   "futuro":{"eu":"chamarei","tu":"chamarás","ele":"chamará","nos":"chamaremos","vcs":"chamarão"}}},
  {"id":270,"pt":"usar","en":"to use","pos":"verb","level":5,"arc":2,
   "sentences":[{"pt":"Você usa o metrô todo dia?","en":"Do you use the subway every day?"},
                {"pt":"Usa protetor solar na praia!","en":"Use sunscreen at the beach!"}],
   "conjugations":{"presente":{"eu":"uso","tu":"usas","ele":"usa","nos":"usamos","vcs":"usam"},
                   "perfeito":{"eu":"usei","tu":"usaste","ele":"usou","nos":"usamos","vcs":"usaram"},
                   "imperfeito":{"eu":"usava","tu":"usavas","ele":"usava","nos":"usávamos","vcs":"usavam"},
                   "futuro":{"eu":"usarei","tu":"usarás","ele":"usará","nos":"usaremos","vcs":"usarão"}}},

  # ── LEVEL 6 · Arc 2 · Rio – A Praia (Body + Physical) ───────────────────
  {"id":271,"pt":"rosto","en":"face","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Ela tem um rosto muito expressivo.","en":"She has a very expressive face."},
                {"pt":"O sol queimou meu rosto na praia.","en":"The sun burned my face at the beach."}]},
  {"id":272,"pt":"nariz","en":"nose","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Estou com o nariz entupido.","en":"My nose is stuffy."},
                {"pt":"Ele tem o nariz do pai.","en":"He has his father's nose."}]},
  {"id":273,"pt":"orelha","en":"ear","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Coloca o fone na orelha.","en":"Put the earphone in your ear."},
                {"pt":"Minha orelha está doendo.","en":"My ear hurts."}]},
  {"id":274,"pt":"pescoço","en":"neck","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Estou com dor no pescoço.","en":"I have a pain in my neck."},
                {"pt":"Ela usava um colar no pescoço.","en":"She was wearing a necklace around her neck."}]},
  {"id":275,"pt":"ombro","en":"shoulder","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Ele colocou a mochila no ombro.","en":"He put the backpack on his shoulder."},
                {"pt":"Sinto dor no ombro direito.","en":"I feel pain in my right shoulder."}]},
  {"id":276,"pt":"braço","en":"arm","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Ela me abraçou com os dois braços.","en":"She hugged me with both arms."},
                {"pt":"O sol deixou meu braço vermelho.","en":"The sun left my arm red."}]},
  {"id":277,"pt":"dedo","en":"finger / toe","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Machuquei o dedo na porta.","en":"I hurt my finger on the door."},
                {"pt":"Ela conta nos dedos.","en":"She counts on her fingers."}]},
  {"id":278,"pt":"peito","en":"chest","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Sinto uma pressão no peito.","en":"I feel pressure in my chest."},
                {"pt":"Ele bateu no peito com orgulho.","en":"He beat his chest with pride."}]},
  {"id":279,"pt":"costas","en":"back (body)","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Estou com dor nas costas de tanto sentar.","en":"My back hurts from sitting so much."},
                {"pt":"Passa protetor nas minhas costas?","en":"Can you put sunscreen on my back?"}]},
  {"id":280,"pt":"perna","en":"leg","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Minhas pernas estão cansadas depois da caminhada.","en":"My legs are tired after the walk."},
                {"pt":"Ele quebrou a perna jogando futebol.","en":"He broke his leg playing soccer."}]},
  {"id":281,"pt":"joelho","en":"knee","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Machucou o joelho na queda.","en":"He hurt his knee in the fall."},
                {"pt":"A água chegou até o joelho.","en":"The water came up to my knee."}]},
  {"id":282,"pt":"cabelo","en":"hair","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Ela tem cabelo longo e cacheado.","en":"She has long, curly hair."},
                {"pt":"O vento bagunçou meu cabelo.","en":"The wind messed up my hair."}]},
  {"id":283,"pt":"dente","en":"tooth","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Preciso ir ao dentista, estou com dor de dente.","en":"I need to go to the dentist, I have a toothache."},
                {"pt":"Escova os dentes três vezes ao dia.","en":"Brush your teeth three times a day."}]},
  {"id":284,"pt":"língua","en":"tongue / language","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"O português é uma língua linda.","en":"Portuguese is a beautiful language."},
                {"pt":"A comida estava tão quente que queimou minha língua.","en":"The food was so hot it burned my tongue."}]},
  {"id":285,"pt":"areia","en":"sand","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"A areia de Ipanema é muito fina.","en":"The sand at Ipanema is very fine."},
                {"pt":"Entrou areia no meu tênis.","en":"Sand got into my sneaker."}]},
  {"id":286,"pt":"onda","en":"wave","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"As ondas hoje estão ótimas para surfar.","en":"The waves today are great for surfing."},
                {"pt":"Uma onda grande me derrubou.","en":"A big wave knocked me down."}]},
  {"id":287,"pt":"calor","en":"heat / warmth","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Que calor! Vamos entrar no mar.","en":"What heat! Let's go into the sea."},
                {"pt":"O calor do Rio é intenso no verão.","en":"The heat in Rio is intense in summer."}]},
  {"id":288,"pt":"sombra","en":"shade / shadow","pos":"noun","level":6,"arc":2,
   "sentences":[{"pt":"Senta na sombra, está muito quente.","en":"Sit in the shade, it's very hot."},
                {"pt":"A sombra da árvore nos protegeu do sol.","en":"The tree's shade protected us from the sun."}]},
  {"id":289,"pt":"alto","en":"tall / high / loud","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Ele é muito alto, deve ter dois metros.","en":"He is very tall, must be two meters."},
                {"pt":"Abaixa o volume, está muito alto.","en":"Turn down the volume, it's too loud."}]},
  {"id":290,"pt":"baixo","en":"short / low / soft (volume)","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Ela é baixa, mas cheia de energia.","en":"She is short, but full of energy."},
                {"pt":"Fala mais baixo, as crianças estão dormindo.","en":"Speak more softly, the children are sleeping."}]},
  {"id":291,"pt":"forte","en":"strong / intense","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"O vento está muito forte hoje.","en":"The wind is very strong today."},
                {"pt":"Ela é forte e corajosa.","en":"She is strong and courageous."}]},
  {"id":292,"pt":"fraco","en":"weak / mild","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"O sinal do celular está fraco aqui.","en":"The cell signal is weak here."},
                {"pt":"Ele ficou fraco depois da doença.","en":"He became weak after the illness."}]},
  {"id":293,"pt":"pesado","en":"heavy","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Essa mala está muito pesada.","en":"This suitcase is very heavy."},
                {"pt":"A comida estava boa mas muito pesada.","en":"The food was good but very heavy."}]},
  {"id":294,"pt":"leve","en":"light (weight) / mild","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Prefiro uma refeição leve no almoço.","en":"I prefer a light meal for lunch."},
                {"pt":"A mochila está leve hoje.","en":"The backpack is light today."}]},
  {"id":295,"pt":"sujo","en":"dirty","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Meu tênis ficou todo sujo de areia.","en":"My sneaker got all dirty with sand."},
                {"pt":"Não entra com sapato sujo na casa.","en":"Don't come in with dirty shoes."}]},
  {"id":296,"pt":"limpo","en":"clean","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"O apartamento estava limpo e organizado.","en":"The apartment was clean and organized."},
                {"pt":"Quero uma roupa limpa para sair.","en":"I want clean clothes to go out."}]},
  {"id":297,"pt":"cheio","en":"full","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"O metrô estava cheio na hora do rush.","en":"The subway was full during rush hour."},
                {"pt":"Estou cheio, comi demais.","en":"I'm full, I ate too much."}]},
  {"id":298,"pt":"vazio","en":"empty","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"A praia estava vazia de manhã cedo.","en":"The beach was empty early in the morning."},
                {"pt":"Minha garrafa está vazia.","en":"My bottle is empty."}]},
  {"id":299,"pt":"gostoso","en":"delicious / nice / good (colloquial)","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"Esse açaí está muito gostoso!","en":"This açaí is delicious!"},
                {"pt":"Foi um dia muito gostoso na praia.","en":"It was a really nice day at the beach."}]},
  {"id":300,"pt":"ruim","en":"bad / poor quality","pos":"adjective","level":6,"arc":2,
   "sentences":[{"pt":"O tempo está ruim, vai chover.","en":"The weather is bad, it's going to rain."},
                {"pt":"Esse filme foi muito ruim.","en":"That movie was really bad."}]},
  {"id":301,"pt":"nadar","en":"to swim","pos":"verb","level":6,"arc":2,
   "sentences":[{"pt":"Vamos nadar no mar?","en":"Shall we swim in the sea?"},
                {"pt":"Ela nada todos os dias na piscina.","en":"She swims every day in the pool."}],
   "conjugations":{"presente":{"eu":"nado","tu":"nadas","ele":"nada","nos":"nadamos","vcs":"nadam"},
                   "perfeito":{"eu":"nadei","tu":"nadaste","ele":"nadou","nos":"nadamos","vcs":"nadaram"},
                   "imperfeito":{"eu":"nadava","tu":"nadavas","ele":"nadava","nos":"nadávamos","vcs":"nadavam"},
                   "futuro":{"eu":"nadarei","tu":"nadarás","ele":"nadará","nos":"nadaremos","vcs":"nadarão"}}},
  {"id":302,"pt":"olhar","en":"to look / to watch","pos":"verb","level":6,"arc":2,
   "sentences":[{"pt":"Olha que vista linda!","en":"Look what a beautiful view!"},
                {"pt":"Ele olhou para mim e sorriu.","en":"He looked at me and smiled."}],
   "conjugations":{"presente":{"eu":"olho","tu":"olhas","ele":"olha","nos":"olhamos","vcs":"olham"},
                   "perfeito":{"eu":"olhei","tu":"olhaste","ele":"olhou","nos":"olhamos","vcs":"olharam"},
                   "imperfeito":{"eu":"olhava","tu":"olhavas","ele":"olhava","nos":"olhávamos","vcs":"olhavam"},
                   "futuro":{"eu":"olharei","tu":"olharás","ele":"olhará","nos":"olharemos","vcs":"olharão"}}},
  {"id":303,"pt":"escutar","en":"to listen / to hear","pos":"verb","level":6,"arc":2,
   "sentences":[{"pt":"Escuta essa música, é demais!","en":"Listen to this music, it's amazing!"},
                {"pt":"Não consigo escutar com esse barulho.","en":"I can't hear with all this noise."}],
   "conjugations":{"presente":{"eu":"escuto","tu":"escutas","ele":"escuta","nos":"escutamos","vcs":"escutam"},
                   "perfeito":{"eu":"escutei","tu":"escutaste","ele":"escutou","nos":"escutamos","vcs":"escutaram"},
                   "imperfeito":{"eu":"escutava","tu":"escutavas","ele":"escutava","nos":"escutávamos","vcs":"escutavam"},
                   "futuro":{"eu":"escutarei","tu":"escutarás","ele":"escutará","nos":"escutaremos","vcs":"escutarão"}}},
  {"id":304,"pt":"tocar","en":"to touch / to play (instrument)","pos":"verb","level":6,"arc":2,
   "sentences":[{"pt":"Ele toca violão muito bem.","en":"He plays guitar very well."},
                {"pt":"Não toca nisso, está quente.","en":"Don't touch that, it's hot."}],
   "conjugations":{"presente":{"eu":"toco","tu":"tocas","ele":"toca","nos":"tocamos","vcs":"tocam"},
                   "perfeito":{"eu":"toquei","tu":"tocaste","ele":"tocou","nos":"tocamos","vcs":"tocaram"},
                   "imperfeito":{"eu":"tocava","tu":"tocavas","ele":"tocava","nos":"tocávamos","vcs":"tocavam"},
                   "futuro":{"eu":"tocarei","tu":"tocarás","ele":"tocará","nos":"tocaremos","vcs":"tocarão"}}},
  {"id":305,"pt":"gritar","en":"to shout / to yell","pos":"verb","level":6,"arc":2,
   "sentences":[{"pt":"Por que você está gritando?","en":"Why are you shouting?"},
                {"pt":"A torcida gritou quando o Brasil marcou.","en":"The fans yelled when Brazil scored."}],
   "conjugations":{"presente":{"eu":"grito","tu":"gritas","ele":"grita","nos":"gritamos","vcs":"gritam"},
                   "perfeito":{"eu":"gritei","tu":"gritaste","ele":"gritou","nos":"gritamos","vcs":"gritaram"},
                   "imperfeito":{"eu":"gritava","tu":"gritavas","ele":"gritava","nos":"gritávamos","vcs":"gritavam"},
                   "futuro":{"eu":"gritarei","tu":"gritarás","ele":"gritará","nos":"gritaremos","vcs":"gritarão"}}},

  # ── LEVEL 7 · Arc 2 · Rio – O Boteco (Food, Social, Daily Life) ─────────
  {"id":306,"pt":"arroz","en":"rice","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Arroz e feijão é o prato típico brasileiro.","en":"Rice and beans is the typical Brazilian dish."},
                {"pt":"Coloca mais arroz no meu prato.","en":"Put more rice on my plate."}]},
  {"id":307,"pt":"feijão","en":"beans","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Tem feijão preto hoje?","en":"Is there black beans today?"},
                {"pt":"A feijoada leva feijão preto com carne.","en":"Feijoada uses black beans with meat."}]},
  {"id":308,"pt":"carne","en":"meat","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Você come carne ou é vegetariano?","en":"Do you eat meat or are you vegetarian?"},
                {"pt":"A carne de churrasco estava deliciosa.","en":"The barbecue meat was delicious."}]},
  {"id":309,"pt":"frango","en":"chicken","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Prefiro frango a carne vermelha.","en":"I prefer chicken to red meat."},
                {"pt":"Frango assado com arroz, por favor.","en":"Roasted chicken with rice, please."}]},
  {"id":310,"pt":"peixe","en":"fish","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Tem peixe fresco na feira.","en":"There's fresh fish at the market."},
                {"pt":"Ela não come peixe, só carne.","en":"She doesn't eat fish, only meat."}]},
  {"id":311,"pt":"fruta","en":"fruit","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"O Brasil tem frutas incríveis como manga e maracujá.","en":"Brazil has incredible fruits like mango and passion fruit."},
                {"pt":"Como fruta todo dia no café da manhã.","en":"I eat fruit every day at breakfast."}]},
  {"id":312,"pt":"legume","en":"vegetable","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Preciso comer mais legumes e verduras.","en":"I need to eat more vegetables and greens."},
                {"pt":"Quais legumes você gosta?","en":"Which vegetables do you like?"}]},
  {"id":313,"pt":"suco","en":"juice","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Um suco de laranja, por favor.","en":"An orange juice, please."},
                {"pt":"O suco de maracujá é refrescante.","en":"Passion fruit juice is refreshing."}]},
  {"id":314,"pt":"leite","en":"milk","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Você quer café com leite ou puro?","en":"Do you want coffee with milk or black?"},
                {"pt":"Compra mais leite no mercado.","en":"Buy more milk at the market."}]},
  {"id":315,"pt":"cerveja","en":"beer","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Uma cerveja bem gelada, por favor.","en":"A very cold beer, please."},
                {"pt":"No boteco a cerveja sempre está gelada.","en":"At the bar the beer is always ice cold."}]},
  {"id":316,"pt":"vinho","en":"wine","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Você prefere vinho tinto ou branco?","en":"Do you prefer red or white wine?"},
                {"pt":"Trouxe um vinho para o jantar.","en":"I brought a wine for dinner."}]},
  {"id":317,"pt":"almoço","en":"lunch","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"A gente vai almoçar juntos hoje?","en":"Are we having lunch together today?"},
                {"pt":"O almoço no Brasil costuma ser a refeição principal.","en":"Lunch in Brazil is usually the main meal."}]},
  {"id":318,"pt":"jantar","en":"dinner","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"O jantar está pronto, pode vir.","en":"Dinner is ready, you can come."},
                {"pt":"Jantamos num restaurante italiano ontem.","en":"We had dinner at an Italian restaurant yesterday."}]},
  {"id":319,"pt":"sobremesa","en":"dessert","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Tem bolo de chocolate de sobremesa.","en":"There's chocolate cake for dessert."},
                {"pt":"Não consigo recusar sobremesa.","en":"I can't refuse dessert."}]},
  {"id":320,"pt":"prato","en":"plate / dish","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Esse é o prato típico da Bahia.","en":"This is the typical dish from Bahia."},
                {"pt":"Lava o prato depois que comer.","en":"Wash the plate after you eat."}]},
  {"id":321,"pt":"copo","en":"glass / cup","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Me dá um copo de água?","en":"Can you give me a glass of water?"},
                {"pt":"Quebrei o copo sem querer.","en":"I accidentally broke the glass."}]},
  {"id":322,"pt":"garfo","en":"fork","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Cadê o garfo? Só tem colher.","en":"Where's the fork? There's only a spoon."},
                {"pt":"No Brasil come-se com garfo e faca.","en":"In Brazil people eat with fork and knife."}]},
  {"id":323,"pt":"faca","en":"knife","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Preciso de uma faca para cortar a carne.","en":"I need a knife to cut the meat."},
                {"pt":"Cuidado com a faca, está afiada.","en":"Be careful with the knife, it's sharp."}]},
  {"id":324,"pt":"colher","en":"spoon","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Mexe o café com a colher.","en":"Stir the coffee with the spoon."},
                {"pt":"Usa a colher para comer o arroz.","en":"Use the spoon to eat the rice."}]},
  {"id":325,"pt":"cardápio","en":"menu","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Pode me trazer o cardápio?","en":"Can you bring me the menu?"},
                {"pt":"O cardápio está em português, você entende?","en":"The menu is in Portuguese, do you understand?"}]},
  {"id":326,"pt":"gorjeta","en":"tip (gratuity)","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"A gorjeta já está incluída na conta?","en":"Is the tip already included in the bill?"},
                {"pt":"Deixei dez por cento de gorjeta.","en":"I left a ten percent tip."}]},
  {"id":327,"pt":"garçom","en":"waiter","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Garçom, pode trazer mais água?","en":"Waiter, can you bring more water?"},
                {"pt":"O garçom foi muito atencioso.","en":"The waiter was very attentive."}]},
  {"id":328,"pt":"mesa","en":"table","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Tem uma mesa livre para dois?","en":"Is there a free table for two?"},
                {"pt":"Coloca os pratos na mesa.","en":"Put the dishes on the table."}]},
  {"id":329,"pt":"cadeira","en":"chair","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Puxa uma cadeira e senta.","en":"Pull up a chair and sit down."},
                {"pt":"Essa cadeira está quebrada.","en":"This chair is broken."}]},
  {"id":330,"pt":"sala","en":"living room / room","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"A família se reuniu na sala para assistir tv.","en":"The family gathered in the living room to watch TV."},
                {"pt":"A reunião é na sala de conferências.","en":"The meeting is in the conference room."}]},
  {"id":331,"pt":"cozinha","en":"kitchen","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"O cheiro que vem da cozinha está ótimo.","en":"The smell coming from the kitchen is great."},
                {"pt":"Ela fica horas na cozinha cozinhando.","en":"She spends hours in the kitchen cooking."}]},
  {"id":332,"pt":"janela","en":"window","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Abre a janela, está muito abafado aqui.","en":"Open the window, it's very stuffy here."},
                {"pt":"Da janela do hotel dá para ver o mar.","en":"From the hotel window you can see the sea."}]},
  {"id":333,"pt":"porta","en":"door","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Fecha a porta ao sair.","en":"Close the door when you leave."},
                {"pt":"Bate na porta antes de entrar.","en":"Knock on the door before entering."}]},
  {"id":334,"pt":"vizinho","en":"neighbor","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Meu vizinho toca violão à noite.","en":"My neighbor plays guitar at night."},
                {"pt":"Os vizinhos são muito simpáticos.","en":"The neighbors are very friendly."}]},
  {"id":335,"pt":"festa","en":"party","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Vai ter festa de aniversário no sábado.","en":"There's going to be a birthday party on Saturday."},
                {"pt":"A festa foi até de madrugada.","en":"The party went until the early morning."}]},
  {"id":336,"pt":"bar","en":"bar / pub","pos":"noun","level":7,"arc":2,
   "sentences":[{"pt":"Vamos a um bar depois do trabalho?","en":"Shall we go to a bar after work?"},
                {"pt":"O bar na esquina tem a melhor caipirinha.","en":"The bar on the corner has the best caipirinha."}]},
  {"id":337,"pt":"pedir","en":"to order / to ask for / to request","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Vou pedir um frango com arroz.","en":"I'm going to order chicken with rice."},
                {"pt":"Ela pediu ajuda ao garçom.","en":"She asked the waiter for help."}],
   "conjugations":{"presente":{"eu":"peço","tu":"pedes","ele":"pede","nos":"pedimos","vcs":"pedem"},
                   "perfeito":{"eu":"pedi","tu":"pediste","ele":"pediu","nos":"pedimos","vcs":"pediram"},
                   "imperfeito":{"eu":"pedia","tu":"pedias","ele":"pedia","nos":"pedíamos","vcs":"pediam"},
                   "futuro":{"eu":"pedirei","tu":"pedirás","ele":"pedirá","nos":"pediremos","vcs":"pedirão"}}},
  {"id":338,"pt":"cozinhar","en":"to cook","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Você sabe cozinhar comida brasileira?","en":"Do you know how to cook Brazilian food?"},
                {"pt":"Cozinhei feijão e arroz para o almoço.","en":"I cooked beans and rice for lunch."}],
   "conjugations":{"presente":{"eu":"cozinho","tu":"cozinhas","ele":"cozinha","nos":"cozinhamos","vcs":"cozinham"},
                   "perfeito":{"eu":"cozinhei","tu":"cozinhaste","ele":"cozinhou","nos":"cozinhamos","vcs":"cozinharam"},
                   "imperfeito":{"eu":"cozinhava","tu":"cozinhavas","ele":"cozinhava","nos":"cozinhávamos","vcs":"cozinhavam"},
                   "futuro":{"eu":"cozinharei","tu":"cozinharás","ele":"cozinhará","nos":"cozinharemos","vcs":"cozinharão"}}},
  {"id":339,"pt":"dividir","en":"to split / to divide / to share","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Vamos dividir a conta?","en":"Shall we split the bill?"},
                {"pt":"Dividimos o apartamento com mais dois amigos.","en":"We share the apartment with two other friends."}],
   "conjugations":{"presente":{"eu":"divido","tu":"divides","ele":"divide","nos":"dividimos","vcs":"dividem"},
                   "perfeito":{"eu":"dividi","tu":"dividiste","ele":"dividiu","nos":"dividimos","vcs":"dividiram"},
                   "imperfeito":{"eu":"dividia","tu":"dividias","ele":"dividia","nos":"dividíamos","vcs":"dividiam"},
                   "futuro":{"eu":"dividirei","tu":"dividirás","ele":"dividirá","nos":"dividiremos","vcs":"dividirão"}}},
  {"id":340,"pt":"convidar","en":"to invite","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Vou te convidar para o meu aniversário.","en":"I'm going to invite you to my birthday."},
                {"pt":"Ela me convidou para jantar na casa dela.","en":"She invited me to have dinner at her place."}],
   "conjugations":{"presente":{"eu":"convido","tu":"convidas","ele":"convida","nos":"convidamos","vcs":"convidam"},
                   "perfeito":{"eu":"convidei","tu":"convidaste","ele":"convidou","nos":"convidamos","vcs":"convidaram"},
                   "imperfeito":{"eu":"convidava","tu":"convidavas","ele":"convidava","nos":"convidávamos","vcs":"convidavam"},
                   "futuro":{"eu":"convidarei","tu":"convidarás","ele":"convidará","nos":"convidaremos","vcs":"convidarão"}}},
  {"id":341,"pt":"reservar","en":"to reserve / to book","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Já reservei mesa para as oito.","en":"I already reserved a table for eight o'clock."},
                {"pt":"Preciso reservar um quarto no hotel.","en":"I need to book a room at the hotel."}],
   "conjugations":{"presente":{"eu":"reservo","tu":"reservas","ele":"reserva","nos":"reservamos","vcs":"reservam"},
                   "perfeito":{"eu":"reservei","tu":"reservaste","ele":"reservou","nos":"reservamos","vcs":"reservaram"},
                   "imperfeito":{"eu":"reservava","tu":"reservavas","ele":"reservava","nos":"reservávamos","vcs":"reservavam"},
                   "futuro":{"eu":"reservarei","tu":"reservarás","ele":"reservará","nos":"reservaremos","vcs":"reservarão"}}},
  {"id":342,"pt":"cantar","en":"to sing","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Todo mundo canta no carnaval.","en":"Everyone sings at carnival."},
                {"pt":"Ela canta muito bem.","en":"She sings very well."}],
   "conjugations":{"presente":{"eu":"canto","tu":"cantas","ele":"canta","nos":"cantamos","vcs":"cantam"},
                   "perfeito":{"eu":"cantei","tu":"cantaste","ele":"cantou","nos":"cantamos","vcs":"cantaram"},
                   "imperfeito":{"eu":"cantava","tu":"cantavas","ele":"cantava","nos":"cantávamos","vcs":"cantavam"},
                   "futuro":{"eu":"cantarei","tu":"cantarás","ele":"cantará","nos":"cantaremos","vcs":"cantarão"}}},
  {"id":343,"pt":"dançar","en":"to dance","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Você sabe dançar samba?","en":"Do you know how to dance samba?"},
                {"pt":"A gente dançou a noite toda.","en":"We danced all night."}],
   "conjugations":{"presente":{"eu":"danço","tu":"danças","ele":"dança","nos":"dançamos","vcs":"dançam"},
                   "perfeito":{"eu":"dancei","tu":"dançaste","ele":"dançou","nos":"dançamos","vcs":"dançaram"},
                   "imperfeito":{"eu":"dançava","tu":"dançavas","ele":"dançava","nos":"dançávamos","vcs":"dançavam"},
                   "futuro":{"eu":"dançarei","tu":"dançarás","ele":"dançará","nos":"dançaremos","vcs":"dançarão"}}},
  {"id":344,"pt":"escrever","en":"to write","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Escreve o número do celular aqui.","en":"Write the cell phone number here."},
                {"pt":"Ela escreve um diário todo dia.","en":"She writes a diary every day."}],
   "conjugations":{"presente":{"eu":"escrevo","tu":"escreves","ele":"escreve","nos":"escrevemos","vcs":"escrevem"},
                   "perfeito":{"eu":"escrevi","tu":"escreveste","ele":"escreveu","nos":"escrevemos","vcs":"escreveram"},
                   "imperfeito":{"eu":"escrevia","tu":"escrevias","ele":"escrevia","nos":"escrevíamos","vcs":"escreviam"},
                   "futuro":{"eu":"escreverei","tu":"escreverás","ele":"escreverá","nos":"escreveremos","vcs":"escreverão"}}},
  {"id":345,"pt":"ler","en":"to read","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Gosto de ler na praia.","en":"I like to read at the beach."},
                {"pt":"Você leu as instruções?","en":"Did you read the instructions?"}],
   "conjugations":{"presente":{"eu":"leio","tu":"lês","ele":"lê","nos":"lemos","vcs":"leem"},
                   "perfeito":{"eu":"li","tu":"leste","ele":"leu","nos":"lemos","vcs":"leram"},
                   "imperfeito":{"eu":"lia","tu":"lias","ele":"lia","nos":"líamos","vcs":"liam"},
                   "futuro":{"eu":"lerei","tu":"lerás","ele":"lerá","nos":"leremos","vcs":"lerão"}}},
  {"id":346,"pt":"criar","en":"to create / to raise (children/animals)","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Ela criou os filhos sozinha.","en":"She raised her children alone."},
                {"pt":"Vamos criar um plano juntos.","en":"Let's create a plan together."}],
   "conjugations":{"presente":{"eu":"crio","tu":"crias","ele":"cria","nos":"criamos","vcs":"criam"},
                   "perfeito":{"eu":"criei","tu":"criaste","ele":"criou","nos":"criamos","vcs":"criaram"},
                   "imperfeito":{"eu":"criava","tu":"criavas","ele":"criava","nos":"criávamos","vcs":"criavam"},
                   "futuro":{"eu":"criarei","tu":"criarás","ele":"criará","nos":"criaremos","vcs":"criarão"}}},
  {"id":347,"pt":"resolver","en":"to solve / to resolve","pos":"verb","level":7,"arc":2,
   "sentences":[{"pt":"Temos que resolver esse problema hoje.","en":"We have to solve this problem today."},
                {"pt":"Resolvemos tudo sem briga.","en":"We resolved everything without a fight."}],
   "conjugations":{"presente":{"eu":"resolvo","tu":"resolves","ele":"resolve","nos":"resolvemos","vcs":"resolvem"},
                   "perfeito":{"eu":"resolvi","tu":"resolveste","ele":"resolveu","nos":"resolvemos","vcs":"resolveram"},
                   "imperfeito":{"eu":"resolvia","tu":"resolvias","ele":"resolvia","nos":"resolvíamos","vcs":"resolviam"},
                   "futuro":{"eu":"resolverei","tu":"resolverás","ele":"resolverá","nos":"resolveremos","vcs":"resolverão"}}},

  # ── LEVEL 8 · Arc 2 · Rio – Saudade (Emotions, Relationships) ───────────
  {"id":348,"pt":"tristeza","en":"sadness","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"A tristeza passou quando ela chegou.","en":"The sadness passed when she arrived."},
                {"pt":"Sinto uma tristeza ao pensar na partida.","en":"I feel a sadness when thinking about leaving."}]},
  {"id":349,"pt":"raiva","en":"anger","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Senti raiva quando perdi o voo.","en":"I felt anger when I missed the flight."},
                {"pt":"Não toma decisões com raiva.","en":"Don't make decisions when angry."}]},
  {"id":350,"pt":"ciúme","en":"jealousy","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Ele tem muito ciúme da namorada.","en":"He is very jealous of his girlfriend."},
                {"pt":"Ciúme em excesso destrói relacionamentos.","en":"Excessive jealousy destroys relationships."}]},
  {"id":351,"pt":"vergonha","en":"shame / embarrassment","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Que vergonha, me esqueci do nome dela.","en":"How embarrassing, I forgot her name."},
                {"pt":"Não tenha vergonha de errar.","en":"Don't be ashamed of making mistakes."}]},
  {"id":352,"pt":"orgulho","en":"pride","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Tenho muito orgulho do meu país.","en":"I have a lot of pride in my country."},
                {"pt":"O pai sentiu orgulho quando o filho se formou.","en":"The father felt proud when his son graduated."}]},
  {"id":353,"pt":"esperança","en":"hope","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"A esperança é a última que morre.","en":"Hope is the last to die."},
                {"pt":"Tenho esperança de falar português fluente.","en":"I have hope of speaking fluent Portuguese."}]},
  {"id":354,"pt":"confiança","en":"confidence / trust","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Tenho confiança em você.","en":"I have confidence in you."},
                {"pt":"A confiança leva tempo para construir.","en":"Trust takes time to build."}]},
  {"id":355,"pt":"carinho","en":"affection / care","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Ela trata todo mundo com muito carinho.","en":"She treats everyone with a lot of affection."},
                {"pt":"Um abraço com carinho vale muito.","en":"A caring hug means a lot."}]},
  {"id":356,"pt":"amizade","en":"friendship","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"A amizade dele comigo dura há dez anos.","en":"His friendship with me has lasted ten years."},
                {"pt":"Amizade verdadeira é rara.","en":"True friendship is rare."}]},
  {"id":357,"pt":"casamento","en":"marriage / wedding","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"O casamento foi na praia ao pôr do sol.","en":"The wedding was on the beach at sunset."},
                {"pt":"Eles têm um casamento muito feliz.","en":"They have a very happy marriage."}]},
  {"id":358,"pt":"abraço","en":"hug","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Um grande abraço para você!","en":"A big hug for you!"},
                {"pt":"O abraço do pai me deu força.","en":"My father's hug gave me strength."}]},
  {"id":359,"pt":"beijo","en":"kiss","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"Um beijo e um abraço para a família.","en":"A kiss and a hug to the family."},
                {"pt":"No Brasil se cumprimenta com um beijo no rosto.","en":"In Brazil you greet with a kiss on the cheek."}]},
  {"id":360,"pt":"sorriso","en":"smile","pos":"noun","level":8,"arc":2,
   "sentences":[{"pt":"O sorriso dela ilumina o ambiente.","en":"Her smile lights up the room."},
                {"pt":"Um sorriso abre muitas portas.","en":"A smile opens many doors."}]},
  {"id":361,"pt":"calmo","en":"calm","pos":"adjective","level":8,"arc":2,
   "sentences":[{"pt":"Fica calmo, vai dar tudo certo.","en":"Stay calm, everything will work out."},
                {"pt":"Ele é uma pessoa muito calma.","en":"He is a very calm person."}]},
  {"id":362,"pt":"nervoso","en":"nervous / anxious","pos":"adjective","level":8,"arc":2,
   "sentences":[{"pt":"Estou nervoso antes da apresentação.","en":"I'm nervous before the presentation."},
                {"pt":"Não fica nervoso, é só uma conversa.","en":"Don't get nervous, it's just a conversation."}]},
  {"id":363,"pt":"orgulhoso","en":"proud","pos":"adjective","level":8,"arc":2,
   "sentences":[{"pt":"Estou muito orgulhoso de você.","en":"I'm very proud of you."},
                {"pt":"Ela se sente orgulhosa do que conquistou.","en":"She feels proud of what she has achieved."}]},
  {"id":364,"pt":"apaixonado","en":"in love / passionate","pos":"adjective","level":8,"arc":2,
   "sentences":[{"pt":"Ele está completamente apaixonado por ela.","en":"He is completely in love with her."},
                {"pt":"Sou apaixonado pelo Brasil.","en":"I'm passionate about Brazil."}]},
  {"id":365,"pt":"abraçar","en":"to hug","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Vai lá abraçar sua mãe.","en":"Go hug your mother."},
                {"pt":"Abraçamos na chegada e na despedida.","en":"We hugged at arrival and departure."}],
   "conjugations":{"presente":{"eu":"abraço","tu":"abraças","ele":"abraça","nos":"abraçamos","vcs":"abraçam"},
                   "perfeito":{"eu":"abracei","tu":"abraçaste","ele":"abraçou","nos":"abraçamos","vcs":"abraçaram"},
                   "imperfeito":{"eu":"abraçava","tu":"abraçavas","ele":"abraçava","nos":"abraçávamos","vcs":"abraçavam"},
                   "futuro":{"eu":"abraçarei","tu":"abraçarás","ele":"abraçará","nos":"abraçaremos","vcs":"abraçarão"}}},
  {"id":366,"pt":"beijar","en":"to kiss","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"No Brasil se beija no rosto ao cumprimentar.","en":"In Brazil you kiss on the cheek when greeting."},
                {"pt":"Ela beijou o bebê na testa.","en":"She kissed the baby on the forehead."}],
   "conjugations":{"presente":{"eu":"beijo","tu":"beijas","ele":"beija","nos":"beijamos","vcs":"beijam"},
                   "perfeito":{"eu":"beijei","tu":"beijaste","ele":"beijou","nos":"beijamos","vcs":"beijaram"},
                   "imperfeito":{"eu":"beijava","tu":"beijavas","ele":"beijava","nos":"beijávamos","vcs":"beijavam"},
                   "futuro":{"eu":"beijarei","tu":"beijarás","ele":"beijará","nos":"beijaremos","vcs":"beijarão"}}},
  {"id":367,"pt":"chorar","en":"to cry","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Ela chorou de emoção no final do filme.","en":"She cried with emotion at the end of the movie."},
                {"pt":"Não chora, tudo vai ficar bem.","en":"Don't cry, everything will be fine."}],
   "conjugations":{"presente":{"eu":"choro","tu":"choras","ele":"chora","nos":"choramos","vcs":"choram"},
                   "perfeito":{"eu":"chorei","tu":"choraste","ele":"chorou","nos":"choramos","vcs":"choraram"},
                   "imperfeito":{"eu":"chorava","tu":"choravas","ele":"chorava","nos":"chorávamos","vcs":"choravam"},
                   "futuro":{"eu":"chorarei","tu":"chorarás","ele":"chorará","nos":"choraremos","vcs":"chorarão"}}},
  {"id":368,"pt":"sentir","en":"to feel / to sense","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Como você está se sentindo?","en":"How are you feeling?"},
                {"pt":"Sinto falta do Brasil quando estou fora.","en":"I miss Brazil when I'm away."}],
   "conjugations":{"presente":{"eu":"sinto","tu":"sentes","ele":"sente","nos":"sentimos","vcs":"sentem"},
                   "perfeito":{"eu":"senti","tu":"sentiste","ele":"sentiu","nos":"sentimos","vcs":"sentiram"},
                   "imperfeito":{"eu":"sentia","tu":"sentias","ele":"sentia","nos":"sentíamos","vcs":"sentiam"},
                   "futuro":{"eu":"sentirei","tu":"sentirás","ele":"sentirá","nos":"sentiremos","vcs":"sentirão"}}},
  {"id":369,"pt":"adorar","en":"to adore / to love (something)","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Adoro a culinária brasileira.","en":"I love Brazilian cuisine."},
                {"pt":"Ela adora dançar forró.","en":"She loves to dance forró."}],
   "conjugations":{"presente":{"eu":"adoro","tu":"adoras","ele":"adora","nos":"adoramos","vcs":"adoram"},
                   "perfeito":{"eu":"adorei","tu":"adoraste","ele":"adorou","nos":"adoramos","vcs":"adoraram"},
                   "imperfeito":{"eu":"adorava","tu":"adoravas","ele":"adorava","nos":"adorávamos","vcs":"adoravam"},
                   "futuro":{"eu":"adorarei","tu":"adorarás","ele":"adorará","nos":"adoraremos","vcs":"adorarão"}}},
  {"id":370,"pt":"odiar","en":"to hate","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Odeio acordar cedo.","en":"I hate waking up early."},
                {"pt":"Ele odiava o trânsito de São Paulo.","en":"He hated the São Paulo traffic."}],
   "conjugations":{"presente":{"eu":"odeio","tu":"odeias","ele":"odeia","nos":"odiamos","vcs":"odeiam"},
                   "perfeito":{"eu":"odiei","tu":"odiaste","ele":"odiou","nos":"odiamos","vcs":"odiaram"},
                   "imperfeito":{"eu":"odiava","tu":"odiavas","ele":"odiava","nos":"odiávamos","vcs":"odiavam"},
                   "futuro":{"eu":"odiarei","tu":"odiarás","ele":"odiará","nos":"odiaremos","vcs":"odiarão"}}},
  {"id":371,"pt":"confiar","en":"to trust","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Confio em você completamente.","en":"I trust you completely."},
                {"pt":"É difícil confiar em pessoas novas.","en":"It's hard to trust new people."}],
   "conjugations":{"presente":{"eu":"confio","tu":"confias","ele":"confia","nos":"confiamos","vcs":"confiam"},
                   "perfeito":{"eu":"confiei","tu":"confiaste","ele":"confiou","nos":"confiamos","vcs":"confiaram"},
                   "imperfeito":{"eu":"confiava","tu":"confiavas","ele":"confiava","nos":"confiávamos","vcs":"confiavam"},
                   "futuro":{"eu":"confiarei","tu":"confiarás","ele":"confiará","nos":"confiaremos","vcs":"confiarão"}}},
  {"id":372,"pt":"perdoar","en":"to forgive","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Conseguiu perdoar o que aconteceu?","en":"Were you able to forgive what happened?"},
                {"pt":"Perdoei, mas não esqueci.","en":"I forgave, but I didn't forget."}],
   "conjugations":{"presente":{"eu":"perdoo","tu":"perdoas","ele":"perdoa","nos":"perdoamos","vcs":"perdoam"},
                   "perfeito":{"eu":"perdoei","tu":"perdoaste","ele":"perdoou","nos":"perdoamos","vcs":"perdoaram"},
                   "imperfeito":{"eu":"perdoava","tu":"perdoavas","ele":"perdoava","nos":"perdoávamos","vcs":"perdoavam"},
                   "futuro":{"eu":"perdoarei","tu":"perdoarás","ele":"perdoará","nos":"perdoaremos","vcs":"perdoarão"}}},
  {"id":373,"pt":"cuidar","en":"to take care of / to look after","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Cuida bem de você, tá?","en":"Take good care of yourself, ok?"},
                {"pt":"Ela cuida dos pais com muito amor.","en":"She takes care of her parents with a lot of love."}],
   "conjugations":{"presente":{"eu":"cuido","tu":"cuidas","ele":"cuida","nos":"cuidamos","vcs":"cuidam"},
                   "perfeito":{"eu":"cuidei","tu":"cuidaste","ele":"cuidou","nos":"cuidamos","vcs":"cuidaram"},
                   "imperfeito":{"eu":"cuidava","tu":"cuidavas","ele":"cuidava","nos":"cuidávamos","vcs":"cuidavam"},
                   "futuro":{"eu":"cuidarei","tu":"cuidarás","ele":"cuidará","nos":"cuidaremos","vcs":"cuidarão"}}},
  {"id":374,"pt":"relaxar","en":"to relax","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Preciso relaxar um pouco.","en":"I need to relax a little."},
                {"pt":"No fim de semana eu só relaxo.","en":"On the weekend I just relax."}],
   "conjugations":{"presente":{"eu":"relaxo","tu":"relaxas","ele":"relaxa","nos":"relaxamos","vcs":"relaxam"},
                   "perfeito":{"eu":"relaxei","tu":"relaxaste","ele":"relaxou","nos":"relaxamos","vcs":"relaxaram"},
                   "imperfeito":{"eu":"relaxava","tu":"relaxavas","ele":"relaxava","nos":"relaxávamos","vcs":"relaxavam"},
                   "futuro":{"eu":"relaxarei","tu":"relaxarás","ele":"relaxará","nos":"relaxaremos","vcs":"relaxarão"}}},
  {"id":375,"pt":"sonhar","en":"to dream","pos":"verb","level":8,"arc":2,
   "sentences":[{"pt":"Sonhei com você essa noite.","en":"I dreamed about you last night."},
                {"pt":"Sonho em morar num país de língua portuguesa.","en":"I dream of living in a Portuguese-speaking country."}],
   "conjugations":{"presente":{"eu":"sonho","tu":"sonhas","ele":"sonha","nos":"sonhamos","vcs":"sonham"},
                   "perfeito":{"eu":"sonhei","tu":"sonhaste","ele":"sonhou","nos":"sonhamos","vcs":"sonharam"},
                   "imperfeito":{"eu":"sonhava","tu":"sonhavas","ele":"sonhava","nos":"sonhávamos","vcs":"sonhavam"},
                   "futuro":{"eu":"sonharei","tu":"sonharás","ele":"sonhará","nos":"sonharemos","vcs":"sonharão"}}},
]

print(json.dumps(words, ensure_ascii=False, indent=2))
print(f"\n# Total new words: {len(words)}", flush=True)
