import json

words = [
  # ── LEVEL 13 · Arc 4 · Bahia – Axé (Music, Spirit, Afro-Brazilian) ──────
  {"id":480,"pt":"ritmo","en":"rhythm","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O ritmo do samba entra no sangue.","en":"The rhythm of samba gets into your blood."},
                {"pt":"Ela tem muito ritmo, dança muito bem.","en":"She has great rhythm, she dances very well."}]},
  {"id":481,"pt":"batida","en":"beat / knock / blend (juice)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A batida do tambor é hipnótica.","en":"The drum beat is hypnotic."},
                {"pt":"Uma batida de maracujá, por favor.","en":"A passion fruit blend, please."}]},
  {"id":482,"pt":"tambor","en":"drum","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"Os tambores do candomblé soam na noite.","en":"The candomblé drums sound through the night."},
                {"pt":"Ele aprendeu a tocar tambor com o avô.","en":"He learned to play drums with his grandfather."}]},
  {"id":483,"pt":"axé","en":"axé (spiritual energy / Afro-Brazilian blessing)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"Axé, que a força te acompanhe.","en":"Axé, may strength be with you."},
                {"pt":"O axé é a energia vital no candomblé.","en":"Axé is the vital energy in candomblé."}]},
  {"id":484,"pt":"samba","en":"samba (dance and music)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O samba nasceu das comunidades africanas no Brasil.","en":"Samba was born from African communities in Brazil."},
                {"pt":"No Rio, o samba é muito mais que uma dança.","en":"In Rio, samba is much more than a dance."}]},
  {"id":485,"pt":"forró","en":"forró (northeastern music/dance)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O forró é a dança típica do nordeste.","en":"Forró is the typical dance of the northeast."},
                {"pt":"Adoro dançar forró com o meu namorado.","en":"I love dancing forró with my boyfriend."}]},
  {"id":486,"pt":"batuque","en":"drumming / percussion beat","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O batuque das escolas de samba é ensurdecedor.","en":"The drumming of samba schools is deafening."},
                {"pt":"O batuque começou e todos levantaram para dançar.","en":"The drumming started and everyone got up to dance."}]},
  {"id":487,"pt":"capoeira","en":"capoeira (Afro-Brazilian martial art/dance)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A capoeira combina luta, dança e música.","en":"Capoeira combines fighting, dance, and music."},
                {"pt":"Aprendi capoeira em Salvador.","en":"I learned capoeira in Salvador."}]},
  {"id":488,"pt":"orixá","en":"orixá (Afro-Brazilian deity)","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"Cada orixá representa uma força da natureza.","en":"Each orixá represents a force of nature."},
                {"pt":"Iemanjá é o orixá do mar.","en":"Iemanjá is the orixá of the sea."}]},
  {"id":489,"pt":"terreiro","en":"candomblé house / courtyard","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O terreiro é um espaço sagrado para o candomblé.","en":"The terreiro is a sacred space for candomblé."},
                {"pt":"As crianças brincam no terreiro da casa.","en":"The children play in the courtyard of the house."}]},
  {"id":490,"pt":"fé","en":"faith","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"O povo baiano tem muita fé.","en":"The people of Bahia have a lot of faith."},
                {"pt":"A fé move montanhas.","en":"Faith moves mountains."}]},
  {"id":491,"pt":"espiritualidade","en":"spirituality","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A espiritualidade faz parte da cultura baiana.","en":"Spirituality is part of Bahian culture."},
                {"pt":"Ele tem uma espiritualidade muito forte.","en":"He has a very strong spirituality."}]},
  {"id":492,"pt":"reza","en":"prayer / chant","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A avó sempre faz sua reza antes de dormir.","en":"Grandma always says her prayer before sleeping."},
                {"pt":"A reza do terreiro começa ao pôr do sol.","en":"The chant at the terreiro begins at sunset."}]},
  {"id":493,"pt":"oferta","en":"offering / offer","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"Deixaram ofertas para Iemanjá na praia.","en":"They left offerings for Iemanjá at the beach."},
                {"pt":"Uma oferta de flores e frutas para os orixás.","en":"An offering of flowers and fruit for the orixás."}]},
  {"id":494,"pt":"alegria","en":"joy / happiness","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A alegria do povo baiano é contagiante.","en":"The joy of the Bahian people is contagious."},
                {"pt":"Sinto uma alegria enorme ao ouvir esse ritmo.","en":"I feel enormous joy when I hear that rhythm."}]},
  {"id":495,"pt":"cor","en":"color","pos":"noun","level":13,"arc":4,
   "sentences":[{"pt":"A Bahia é uma explosão de cor.","en":"Bahia is an explosion of color."},
                {"pt":"Qual é a sua cor preferida?","en":"What is your favorite color?"}]},
  {"id":496,"pt":"vermelho","en":"red","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"O vestido vermelho dela chamou atenção.","en":"Her red dress attracted attention."},
                {"pt":"O céu ficou vermelho ao pôr do sol.","en":"The sky turned red at sunset."}]},
  {"id":497,"pt":"azul","en":"blue","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"O mar de Salvador é azul-turquesa.","en":"The sea in Salvador is turquoise blue."},
                {"pt":"Ela tem olhos azuis.","en":"She has blue eyes."}]},
  {"id":498,"pt":"verde","en":"green","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"A bandeira do Brasil é verde e amarela.","en":"Brazil's flag is green and yellow."},
                {"pt":"A natureza baiana é muito verde.","en":"Bahian nature is very green."}]},
  {"id":499,"pt":"amarelo","en":"yellow","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"O ipê amarelo floresce por todo o Brasil.","en":"The yellow ipê tree blooms throughout Brazil."},
                {"pt":"A camisa amarela da seleção é icônica.","en":"The yellow national team shirt is iconic."}]},
  {"id":500,"pt":"branco","en":"white","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"No candomblé, roupa branca é símbolo de paz.","en":"In candomblé, white clothing is a symbol of peace."},
                {"pt":"A areia branca de Trancoso é famosa.","en":"The white sand of Trancoso is famous."}]},
  {"id":501,"pt":"preto","en":"black","pos":"adjective","level":13,"arc":4,
   "sentences":[{"pt":"Feijão preto com arroz é o prato nacional.","en":"Black beans with rice is the national dish."},
                {"pt":"Ela usa um vestido preto elegante.","en":"She's wearing an elegant black dress."}]},
  {"id":502,"pt":"rezar","en":"to pray / to chant","pos":"verb","level":13,"arc":4,
   "sentences":[{"pt":"A avó reza toda manhã.","en":"Grandma prays every morning."},
                {"pt":"Rezamos pela saúde da família.","en":"We prayed for the family's health."}],
   "conjugations":{"presente":{"eu":"rezo","tu":"rezas","ele":"reza","nos":"rezamos","vcs":"rezam"},
                   "perfeito":{"eu":"rezei","tu":"rezaste","ele":"rezou","nos":"rezamos","vcs":"rezaram"},
                   "imperfeito":{"eu":"rezava","tu":"rezavas","ele":"rezava","nos":"rezávamos","vcs":"rezavam"},
                   "futuro":{"eu":"rezarei","tu":"rezarás","ele":"rezará","nos":"rezaremos","vcs":"rezarão"}}},
  {"id":503,"pt":"tocar","en":"to touch / to play instrument","pos":"verb","level":13,"arc":4,
   "sentences":[{"pt":"Ele toca berimbau há vinte anos.","en":"He has been playing the berimbau for twenty years."},
                {"pt":"Não toca nos objetos sagrados.","en":"Don't touch the sacred objects."}],
   "conjugations":{"presente":{"eu":"toco","tu":"tocas","ele":"toca","nos":"tocamos","vcs":"tocam"},
                   "perfeito":{"eu":"toquei","tu":"tocaste","ele":"tocou","nos":"tocamos","vcs":"tocaram"},
                   "imperfeito":{"eu":"tocava","tu":"tocavas","ele":"tocava","nos":"tocávamos","vcs":"tocavam"},
                   "futuro":{"eu":"tocarei","tu":"tocarás","ele":"tocará","nos":"tocaremos","vcs":"tocarão"}}},

  # ── LEVEL 14 · Arc 4 · Bahia – Raízes Africanas (History, Society) ───────
  {"id":504,"pt":"escravidão","en":"slavery","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A escravidão deixou marcas profundas no Brasil.","en":"Slavery left deep marks on Brazil."},
                {"pt":"O Brasil foi o último país a abolir a escravidão.","en":"Brazil was the last country to abolish slavery."}]},
  {"id":505,"pt":"liberdade","en":"freedom / liberty","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"Zumbi dos Palmares lutou pela liberdade.","en":"Zumbi dos Palmares fought for freedom."},
                {"pt":"A liberdade é o maior bem que existe.","en":"Freedom is the greatest good that exists."}]},
  {"id":506,"pt":"luta","en":"struggle / fight","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A luta pelos direitos civis continua.","en":"The struggle for civil rights continues."},
                {"pt":"A vida é uma luta constante.","en":"Life is a constant struggle."}]},
  {"id":507,"pt":"resistência","en":"resistance","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"O quilombo era um símbolo de resistência.","en":"The quilombo was a symbol of resistance."},
                {"pt":"A resistência cultural preservou as tradições africanas.","en":"Cultural resistance preserved African traditions."}]},
  {"id":508,"pt":"igualdade","en":"equality","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A igualdade racial ainda é um desafio no Brasil.","en":"Racial equality is still a challenge in Brazil."},
                {"pt":"Lutamos pela igualdade de direitos.","en":"We fight for equality of rights."}]},
  {"id":509,"pt":"direito","en":"right (entitlement) / law","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"Educação é um direito de todos.","en":"Education is everyone's right."},
                {"pt":"Ela estudou direito na universidade.","en":"She studied law at university."}]},
  {"id":510,"pt":"povo","en":"people / nation / folk","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"O povo brasileiro é muito acolhedor.","en":"The Brazilian people are very welcoming."},
                {"pt":"O povo tem que ter voz nas decisões.","en":"The people must have a voice in decisions."}]},
  {"id":511,"pt":"sociedade","en":"society","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A sociedade brasileira é muito diversa.","en":"Brazilian society is very diverse."},
                {"pt":"Cada um tem um papel na sociedade.","en":"Everyone has a role in society."}]},
  {"id":512,"pt":"desigualdade","en":"inequality","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A desigualdade social é uma ferida aberta.","en":"Social inequality is an open wound."},
                {"pt":"Reduzir a desigualdade é urgente.","en":"Reducing inequality is urgent."}]},
  {"id":513,"pt":"pobreza","en":"poverty","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A pobreza afeta milhões de brasileiros.","en":"Poverty affects millions of Brazilians."},
                {"pt":"A educação é o caminho para sair da pobreza.","en":"Education is the way out of poverty."}]},
  {"id":514,"pt":"riqueza","en":"wealth / richness","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A riqueza cultural da Bahia é imensa.","en":"Bahia's cultural richness is immense."},
                {"pt":"A riqueza não traz felicidade sozinha.","en":"Wealth alone doesn't bring happiness."}]},
  {"id":515,"pt":"governo","en":"government","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"O governo precisa investir em educação.","en":"The government needs to invest in education."},
                {"pt":"O novo governo tomou posse em janeiro.","en":"The new government took office in January."}]},
  {"id":516,"pt":"política","en":"politics / policy","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"Política é um assunto delicado no Brasil.","en":"Politics is a delicate subject in Brazil."},
                {"pt":"A política de saúde pública melhorou.","en":"The public health policy improved."}]},
  {"id":517,"pt":"história","en":"history / story","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A história da Bahia é ligada à África.","en":"Bahia's history is tied to Africa."},
                {"pt":"Que história interessante você me contou!","en":"What an interesting story you told me!"}]},
  {"id":518,"pt":"cultura","en":"culture","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A cultura baiana influenciou o Brasil inteiro.","en":"Bahian culture influenced the whole of Brazil."},
                {"pt":"Tenho muito interesse na cultura brasileira.","en":"I have a lot of interest in Brazilian culture."}]},
  {"id":519,"pt":"diversidade","en":"diversity","pos":"noun","level":14,"arc":4,
   "sentences":[{"pt":"A diversidade étnica do Brasil é uma riqueza.","en":"Brazil's ethnic diversity is a richness."},
                {"pt":"A empresa valoriza a diversidade.","en":"The company values diversity."}]},
  {"id":520,"pt":"lutar","en":"to fight / to struggle","pos":"verb","level":14,"arc":4,
   "sentences":[{"pt":"Vamos lutar pelos nossos direitos.","en":"Let's fight for our rights."},
                {"pt":"Ela lutou muito para chegar onde está.","en":"She fought hard to get where she is."}],
   "conjugations":{"presente":{"eu":"luto","tu":"lutas","ele":"luta","nos":"lutamos","vcs":"lutam"},
                   "perfeito":{"eu":"lutei","tu":"lutaste","ele":"lutou","nos":"lutamos","vcs":"lutaram"},
                   "imperfeito":{"eu":"lutava","tu":"lutavas","ele":"lutava","nos":"lutávamos","vcs":"lutavam"},
                   "futuro":{"eu":"lutarei","tu":"lutarás","ele":"lutará","nos":"lutaremos","vcs":"lutarão"}}},
  {"id":521,"pt":"preservar","en":"to preserve","pos":"verb","level":14,"arc":4,
   "sentences":[{"pt":"É importante preservar as tradições africanas.","en":"It's important to preserve African traditions."},
                {"pt":"Precisamos preservar a Amazônia.","en":"We need to preserve the Amazon."}],
   "conjugations":{"presente":{"eu":"preservo","tu":"preservas","ele":"preserva","nos":"preservamos","vcs":"preservam"},
                   "perfeito":{"eu":"preservei","tu":"preservaste","ele":"preservou","nos":"preservamos","vcs":"preservaram"},
                   "imperfeito":{"eu":"preservava","tu":"preservavas","ele":"preservava","nos":"preservávamos","vcs":"preservavam"},
                   "futuro":{"eu":"preservarei","tu":"preservarás","ele":"preservará","nos":"preservaremos","vcs":"preservarão"}}},
  {"id":522,"pt":"respeitar","en":"to respect","pos":"verb","level":14,"arc":4,
   "sentences":[{"pt":"Respeita as diferenças culturais.","en":"Respect cultural differences."},
                {"pt":"Eu respeito muito as tradições da Bahia.","en":"I have great respect for Bahia's traditions."}],
   "conjugations":{"presente":{"eu":"respeito","tu":"respeitas","ele":"respeita","nos":"respeitamos","vcs":"respeitam"},
                   "perfeito":{"eu":"respeitei","tu":"respeitaste","ele":"respeitou","nos":"respeitamos","vcs":"respeitaram"},
                   "imperfeito":{"eu":"respeitava","tu":"respeitavas","ele":"respeitava","nos":"respeitávamos","vcs":"respeitavam"},
                   "futuro":{"eu":"respeitarei","tu":"respeitarás","ele":"respeitará","nos":"respeitaremos","vcs":"respeitarão"}}},

  # ── LEVEL 15 · Arc 4 · Bahia – Capoeira (Sport, Body, Ocean) ─────────────
  {"id":523,"pt":"esporte","en":"sport","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O futebol é o esporte mais popular do Brasil.","en":"Soccer is the most popular sport in Brazil."},
                {"pt":"Praticar esporte é ótimo para a saúde.","en":"Playing sport is great for your health."}]},
  {"id":524,"pt":"futebol","en":"soccer / football","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O Brasil é o país do futebol.","en":"Brazil is the country of soccer."},
                {"pt":"A gente joga futebol na praia todo domingo.","en":"We play soccer on the beach every Sunday."}]},
  {"id":525,"pt":"time","en":"team","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"Qual é o seu time de futebol?","en":"What is your soccer team?"},
                {"pt":"O time treina todo dia de manhã.","en":"The team trains every morning."}]},
  {"id":526,"pt":"treino","en":"training / practice session","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O treino começa às seis da manhã.","en":"Training starts at six in the morning."},
                {"pt":"Depois do treino fico exausto.","en":"After training I'm exhausted."}]},
  {"id":527,"pt":"gol","en":"goal (sport)","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O Brasil marcou um gol no segundo tempo.","en":"Brazil scored a goal in the second half."},
                {"pt":"Que gol lindo!","en":"What a beautiful goal!"}]},
  {"id":528,"pt":"bola","en":"ball","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"Chuta a bola para cá.","en":"Kick the ball over here."},
                {"pt":"A bola entrou no gol.","en":"The ball went into the goal."}]},
  {"id":529,"pt":"quadra","en":"court (sports)","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"A quadra de tênis fica no clube.","en":"The tennis court is at the club."},
                {"pt":"Jogamos vôlei na quadra da praia.","en":"We played volleyball on the beach court."}]},
  {"id":530,"pt":"piscina","en":"pool","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O hotel tem piscina com vista para o mar.","en":"The hotel has a pool with a view of the sea."},
                {"pt":"Nado na piscina todo dia.","en":"I swim in the pool every day."}]},
  {"id":531,"pt":"golpe","en":"strike / blow / kick (capoeira)","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O golpe de capoeira foi preciso e elegante.","en":"The capoeira strike was precise and elegant."},
                {"pt":"Ele desviou do golpe com agilidade.","en":"He dodged the strike with agility."}]},
  {"id":532,"pt":"agilidade","en":"agility / speed","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"A capoeira desenvolve agilidade e equilíbrio.","en":"Capoeira develops agility and balance."},
                {"pt":"Ele se move com muita agilidade.","en":"He moves with great agility."}]},
  {"id":533,"pt":"equilíbrio","en":"balance / equilibrium","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"Manter o equilíbrio é fundamental na capoeira.","en":"Maintaining balance is essential in capoeira."},
                {"pt":"Preciso de mais equilíbrio na minha vida.","en":"I need more balance in my life."}]},
  {"id":534,"pt":"maré","en":"tide","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"A maré estava alta quando chegamos.","en":"The tide was high when we arrived."},
                {"pt":"Com a maré baixa, dá para ver o recife.","en":"At low tide, you can see the reef."}]},
  {"id":535,"pt":"recife","en":"reef / Recife (city)","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"O recife de coral é um ecossistema frágil.","en":"The coral reef is a fragile ecosystem."},
                {"pt":"Recife é a capital de Pernambuco.","en":"Recife is the capital of Pernambuco."}]},
  {"id":536,"pt":"mergulho","en":"dive / diving","pos":"noun","level":15,"arc":4,
   "sentences":[{"pt":"Fizemos um mergulho incrível em Morro de São Paulo.","en":"We did an incredible dive at Morro de São Paulo."},
                {"pt":"Ele pratica mergulho há dez anos.","en":"He has been diving for ten years."}]},
  {"id":537,"pt":"treinar","en":"to train / to practice","pos":"verb","level":15,"arc":4,
   "sentences":[{"pt":"Treino capoeira três vezes por semana.","en":"I train capoeira three times a week."},
                {"pt":"O time treinou duro para a final.","en":"The team trained hard for the final."}],
   "conjugations":{"presente":{"eu":"treino","tu":"treinas","ele":"treina","nos":"treinamos","vcs":"treinam"},
                   "perfeito":{"eu":"treinei","tu":"treinaste","ele":"treinou","nos":"treinamos","vcs":"treinaram"},
                   "imperfeito":{"eu":"treinava","tu":"treinavas","ele":"treinava","nos":"treinávamos","vcs":"treinavam"},
                   "futuro":{"eu":"treinarei","tu":"treinarás","ele":"treinará","nos":"treinaremos","vcs":"treinarão"}}},
  {"id":538,"pt":"jogar","en":"to play (sport/game) / to throw","pos":"verb","level":15,"arc":4,
   "sentences":[{"pt":"Você joga futebol?","en":"Do you play soccer?"},
                {"pt":"Joga a bola para mim.","en":"Throw the ball to me."}],
   "conjugations":{"presente":{"eu":"jogo","tu":"jogas","ele":"joga","nos":"jogamos","vcs":"jogam"},
                   "perfeito":{"eu":"joguei","tu":"jogaste","ele":"jogou","nos":"jogamos","vcs":"jogaram"},
                   "imperfeito":{"eu":"jogava","tu":"jogavas","ele":"jogava","nos":"jogávamos","vcs":"jogavam"},
                   "futuro":{"eu":"jogarei","tu":"jogarás","ele":"jogará","nos":"jogaremos","vcs":"jogarão"}}},
  {"id":539,"pt":"mergulhar","en":"to dive / to plunge","pos":"verb","level":15,"arc":4,
   "sentences":[{"pt":"Mergulhamos no recife de manhã.","en":"We dived on the reef in the morning."},
                {"pt":"Ela mergulhou de cabeça no projeto.","en":"She dove headfirst into the project."}],
   "conjugations":{"presente":{"eu":"mergulho","tu":"mergulhas","ele":"mergulha","nos":"mergulhamos","vcs":"mergulham"},
                   "perfeito":{"eu":"mergulhei","tu":"mergulhaste","ele":"mergulhou","nos":"mergulhamos","vcs":"mergulharam"},
                   "imperfeito":{"eu":"mergulhava","tu":"mergulhavas","ele":"mergulhava","nos":"mergulhávamos","vcs":"mergulhavam"},
                   "futuro":{"eu":"mergulharei","tu":"mergulharás","ele":"mergulhará","nos":"mergulharemos","vcs":"mergulharão"}}},
  {"id":540,"pt":"vencer","en":"to win / to overcome","pos":"verb","level":15,"arc":4,
   "sentences":[{"pt":"O Brasil venceu por três a zero.","en":"Brazil won three to nothing."},
                {"pt":"Você vai vencer esse desafio.","en":"You will overcome this challenge."}],
   "conjugations":{"presente":{"eu":"venço","tu":"vences","ele":"vence","nos":"vencemos","vcs":"vencem"},
                   "perfeito":{"eu":"venci","tu":"venceste","ele":"venceu","nos":"vencemos","vcs":"venceram"},
                   "imperfeito":{"eu":"vencia","tu":"vencias","ele":"vencia","nos":"vencíamos","vcs":"venciam"},
                   "futuro":{"eu":"vencerei","tu":"vencerás","ele":"vencerá","nos":"venceremos","vcs":"vencerão"}}},

  # ── LEVEL 16 · Arc 4 · Bahia – Carnaval (Celebration, Crowds, Energy) ────
  {"id":541,"pt":"carnaval","en":"carnival","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"O carnaval da Bahia é o maior do mundo.","en":"Bahia's carnival is the largest in the world."},
                {"pt":"No carnaval todo mundo vira criança.","en":"At carnival everyone becomes a child again."}]},
  {"id":542,"pt":"bloco","en":"carnival block / group","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"O Ilê Aiyê é o bloco mais famoso de Salvador.","en":"Ilê Aiyê is the most famous block in Salvador."},
                {"pt":"Seguimos o bloco pela avenida toda.","en":"We followed the block down the whole avenue."}]},
  {"id":543,"pt":"multidão","en":"crowd","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"A multidão tomou as ruas durante o carnaval.","en":"The crowd took over the streets during carnival."},
                {"pt":"Não gosto muito de multidão.","en":"I don't really like crowds."}]},
  {"id":544,"pt":"fantasia","en":"costume / fantasy","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"Qual é a sua fantasia de carnaval este ano?","en":"What is your carnival costume this year?"},
                {"pt":"Ela foi de rainha do mar.","en":"She went as queen of the sea."}]},
  {"id":545,"pt":"confete","en":"confetti","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"Confete e serpentina por todo lado.","en":"Confetti and streamers everywhere."},
                {"pt":"Os confetes caíam do alto dos prédios.","en":"The confetti fell from the top of the buildings."}]},
  {"id":546,"pt":"trio elétrico","en":"electric truck (carnival float)","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"O trio elétrico passou tocando axé music.","en":"The electric float passed playing axé music."},
                {"pt":"O trio elétrico foi inventado na Bahia.","en":"The electric float was invented in Bahia."}]},
  {"id":547,"pt":"animação","en":"excitement / energy / animation","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"A animação do carnaval contagia todo mundo.","en":"The carnival excitement infects everyone."},
                {"pt":"Ele é a animação das festas.","en":"He is the life of the party."}]},
  {"id":548,"pt":"energia","en":"energy","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"A energia do carnaval é inexplicável.","en":"The energy of carnival is inexplicable."},
                {"pt":"Hoje não tenho muita energia.","en":"I don't have much energy today."}]},
  {"id":549,"pt":"barulho","en":"noise / racket","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"O barulho do carnaval se ouve de longe.","en":"The noise of carnival can be heard from far away."},
                {"pt":"Não consigo dormir com esse barulho.","en":"I can't sleep with this noise."}]},
  {"id":550,"pt":"noite","en":"night / evening","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"A festa durou a noite toda.","en":"The party lasted all night."},
                {"pt":"Boa noite, como você está?","en":"Good evening, how are you?"}]},
  {"id":551,"pt":"madrugada","en":"early hours of the morning / dawn","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"No carnaval a festa vai até de madrugada.","en":"At carnival the party goes until the early hours."},
                {"pt":"Acordei de madrugada sem conseguir dormir.","en":"I woke up in the early hours unable to sleep."}]},
  {"id":552,"pt":"rua","en":"street","pos":"noun","level":16,"arc":4,
   "sentences":[{"pt":"As ruas de Salvador ficam lotadas no carnaval.","en":"The streets of Salvador get packed during carnival."},
                {"pt":"O menino brinca na rua com os amigos.","en":"The boy plays in the street with his friends."}]},
  {"id":553,"pt":"animar","en":"to liven up / to cheer up","pos":"verb","level":16,"arc":4,
   "sentences":[{"pt":"Essa música anima qualquer festa.","en":"This music livens up any party."},
                {"pt":"Vamos animar esse povo!","en":"Let's get this crowd going!"}],
   "conjugations":{"presente":{"eu":"animo","tu":"animas","ele":"anima","nos":"animamos","vcs":"animam"},
                   "perfeito":{"eu":"animei","tu":"animaste","ele":"animou","nos":"animamos","vcs":"animaram"},
                   "imperfeito":{"eu":"animava","tu":"animavas","ele":"animava","nos":"animávamos","vcs":"animavam"},
                   "futuro":{"eu":"animarei","tu":"animarás","ele":"animará","nos":"animaremos","vcs":"animarão"}}},
  {"id":554,"pt":"pular","en":"to jump / to skip","pos":"verb","level":16,"arc":4,
   "sentences":[{"pt":"Pular carnaval é uma tradição.","en":"Celebrating carnival is a tradition."},
                {"pt":"As crianças pulam na cama elástica.","en":"The children jump on the trampoline."}],
   "conjugations":{"presente":{"eu":"pulo","tu":"pulas","ele":"pula","nos":"pulamos","vcs":"pulam"},
                   "perfeito":{"eu":"pulei","tu":"pulaste","ele":"pulou","nos":"pulamos","vcs":"pularam"},
                   "imperfeito":{"eu":"pulava","tu":"pulavas","ele":"pulava","nos":"pulávamos","vcs":"pulavam"},
                   "futuro":{"eu":"pularei","tu":"pularás","ele":"pulará","nos":"pularemos","vcs":"pularão"}}},
  {"id":555,"pt":"gritar","en":"to shout / to cheer","pos":"verb","level":16,"arc":4,
   "sentences":[{"pt":"A torcida gritou o nome do jogador.","en":"The crowd shouted the player's name."},
                {"pt":"Gritamos de alegria quando o Brasil ganhou.","en":"We shouted for joy when Brazil won."}],
   "conjugations":{"presente":{"eu":"grito","tu":"gritas","ele":"grita","nos":"gritamos","vcs":"gritam"},
                   "perfeito":{"eu":"gritei","tu":"gritaste","ele":"gritou","nos":"gritamos","vcs":"gritaram"},
                   "imperfeito":{"eu":"gritava","tu":"gritavas","ele":"gritava","nos":"gritávamos","vcs":"gritavam"},
                   "futuro":{"eu":"gritarei","tu":"gritarás","ele":"gritará","nos":"gritaremos","vcs":"gritarão"}}},
]

print(json.dumps(words, ensure_ascii=False, indent=2))
print(f"\n# Total new words: {len(words)}", flush=True)
